### ISSUE TITLE
Redis as save handler

### ISSUE THREAD

**Issue by ikovalyov** [zendframework/zend-session#98]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-session/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-session/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.

### Code to reproduce the issue

```php
                $config->setOption("save_handler", "redis");
                $url = "tcp://" . $redisDto->getHost() . ":" . $redisDto->getPort() . "?auth=" . $redisDto->getPassword() . "&database=1";
                $config->setOption("save_path", $url);
```

### Expected results

It should save data in redis

### Actual results

Warning: session_start(): open(tcp://redis:***?auth=***&amp;database=1/sess_***, O_RDWR) failed: No such file or directory (2) in ***/vendor/zendframework/zend-session/src/SessionManager.php on line 140

Here is what I found in your code:

```
    public function setStorageOption($storageName, $storageValue)
    {
        switch ($storageName) {
            case 'remember_me_seconds':
                // do nothing; not an INI option
                return;
            case 'url_rewriter_tags':
                $key = 'url_rewriter.tags';
                break;
            case 'save_handler':
                // Save handlers must be treated differently due to changes
                // introduced in PHP 7.2. Do not alter running INI setting.
                return $this;
            default:
                $key = 'session.' . $storageName;
                break;
        }
```

The 2.8.0 version looks like 
```
    public function setStorageOption($storageName, $storageValue)
    {
        switch ($storageName) {
            case 'remember_me_seconds':
                // do nothing; not an INI option
                return;
            case 'url_rewriter_tags':
                $key = 'url_rewriter.tags';
                break;
            default:
                $key = 'session.' . $storageName;
                break;
        }
```

If I pass redis as save_handler it's just ignored and php trying to use my redis config as default config parameters. It broken my live servers. Reverted to 2.8.0 for now.

Please fix ASAP.

Thanks.

**Comment by weierophinney** [comment]
Fixed with #99 and released with 2.8.2.

**Comment by ikovalyov** [comment]
Actually it wasn't fixed

v 2.8.2:
```
Warning: session_start(): open(tcp://redis:6379?auth=password&database=1/sess_139bc23a33fc5fdda65bc4b7b9268c69, O_RDWR) failed: No such file or directory (2) in /opt/webapp/***/vendor/zendframework/zend-session/src/SessionManager.php on line 140

Warning: session_start(): Failed to read session data: files (path: tcp://redis:6379?auth=password&database=1) in /opt/webapp/***/vendor/zendframework/zend-session/src/SessionManager.php on line 140
```

v 2.8.0 everything works correctly.
code looks like
```php
                $config->setOption("save_handler", "redis");
                $url = "tcp://" . $redisDto->getHost() . ":" . $redisDto->getPort() . "?auth=" . $redisDto->getPassword() . "&database=1";
                $config->setOption("save_path", $url);
```

**Comment by ikovalyov** [comment]
@weierophinney

**Comment by weierophinney** [comment]
@ikovalyov — Your diagnosis is incorrect.

The change in behavior of `setStorageOption()` is correct; if that change is not present, then the code would call `ini_set('session.save_handler', $value)`, which causes issues within PHP 7.2 in a number of cases.

What we are doing internally instead is, within `setPhpSaveHandler()`, calling `session_module_name($saveHandler)` for built-in save handlers, and `session_set_save_handler()` for any custom save handlers. `getStorageOption()` has been updated to return the value of `session_module_name()` _unless_ a custom save handler was used (in which case, the class name is returned).

I'm going to write a unit test based on your example above, and debug from there; I'll link this to a new pull request once I have a solution ready to review.

**Comment by ikovalyov** [comment]
thanks
